# Generated by Django 3.1.4 on 2021-01-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20210124_2112'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userprofile',
        ),
    ]
