# Generated by Django 3.1.4 on 2021-02-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_cities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cities',
            new_name='Airport',
        ),
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('city', 'airport'), 'verbose_name_plural': 'Airports'},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='Name_of_airport',
            new_name='airport',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='Name_of_city',
            new_name='city',
        ),
    ]
