# Generated by Django 3.1.4 on 2021-02-02 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_auto_20210202_2122'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='airport',
            options={'ordering': ('city', 'airportname'), 'verbose_name_plural': 'Airports'},
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='airport',
            new_name='airportname',
        ),
    ]
