# Generated by Django 3.1.4 on 2021-02-07 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_auto_20210202_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='airport',
            name='airport_latitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='airport',
            name='airport_longitude',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
