# Generated by Django 3.1.4 on 2021-02-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0012_auto_20210207_2047'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airport',
            old_name='airport_latitude',
            new_name='airportLatitude',
        ),
        migrations.RenameField(
            model_name='airport',
            old_name='airport_longitude',
            new_name='airportLongitude',
        ),
    ]
