# Generated by Django 3.1.4 on 2021-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0013_auto_20210207_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airport',
            name='airportLatitude',
            field=models.FloatField(max_length=10),
        ),
        migrations.AlterField(
            model_name='airport',
            name='airportLongitude',
            field=models.FloatField(max_length=10),
        ),
    ]
