# Generated by Django 3.1.4 on 2021-02-11 04:58

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0016_flightorders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flightorders',
            options={'verbose_name_plural': 'Flight Orders'},
        ),
        migrations.AlterModelOptions(
            name='user_querie',
            options={'verbose_name_plural': 'Customer Queries'},
        ),
        migrations.AlterModelManagers(
            name='flightorders',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
