# Generated by Django 3.1.4 on 2021-02-11 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0017_auto_20210211_1028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flightorders',
            managers=[
            ],
        ),
    ]
