# Generated by Django 3.1.4 on 2021-02-11 05:23

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0018_auto_20210211_1028'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flightorders',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
