# Generated by Django 3.1.4 on 2021-02-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0019_auto_20210211_1053'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='flightorders',
            managers=[
            ],
        ),
    ]
