# Generated by Django 3.1.4 on 2021-02-12 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0020_auto_20210211_1056'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flightorders',
        ),
    ]
