# Generated by Django 3.1.4 on 2021-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0022_flightbookingshistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='email',
        ),
        migrations.AddField(
            model_name='flightbookingshistory',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
