# Generated by Django 3.1.4 on 2021-02-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0023_auto_20210212_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='user',
        ),
        migrations.AddField(
            model_name='flightbookingshistory',
            name='username',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
