# Generated by Django 3.1.4 on 2021-02-13 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0024_auto_20210212_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='origin',
        ),
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='price',
        ),
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='username',
        ),
    ]
