# Generated by Django 3.1.4 on 2021-02-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0026_auto_20210213_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbookingshistory',
            old_name='bookingid',
            new_name='userid',
        ),
    ]
