# Generated by Django 3.1.4 on 2021-02-13 09:30

import Profile.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0027_auto_20210213_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightbookingshistory',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='flightbookingshistory',
            name='bookingid',
            field=models.CharField(max_length=500, null=True, verbose_name=Profile.models.userprofile),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
