# Generated by Django 3.1.4 on 2021-02-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0030_auto_20210213_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingshistory',
            name='datetime',
            field=models.DateTimeField(null=True),
        ),
    ]
