# Generated by Django 3.1.4 on 2021-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0031_auto_20210213_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightbookingshistory',
            name='datetime',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
