# Generated by Django 3.1.4 on 2021-02-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0032_auto_20210213_1538'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightbookingshistory',
            old_name='datetime',
            new_name='bookedon',
        ),
        migrations.AddField(
            model_name='flightbookingshistory',
            name='journeydate',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
