# Generated by Django 3.1.4 on 2021-02-13 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0033_auto_20210213_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='state',
            fields=[
                ('state', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='states/')),
            ],
        ),
        migrations.CreateModel(
            name='Points_of_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Point_of_interest', models.CharField(max_length=100, null=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='POIs/')),
                ('category', models.CharField(choices=[('Heritage', 'Heriatge'), ('Outdoors & Adventures', 'Outdoors & Adventures'), ('Shopping & Nightlife', 'Shopping & Nightlife')], max_length=50)),
                ('Short_Description', models.TextField(default='', help_text='Write a short catchy description about the POI in 100 words max', max_length=300)),
                ('city', models.CharField(default='', max_length=50)),
                ('Description', models.TextField(default='', help_text='500 words max', max_length=2000)),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Tips', models.TextField(default='', max_length=300)),
                ('Entry_fees_Adults', models.CharField(default='', max_length=5)),
                ('Entry_fees_Children', models.CharField(default='', max_length=5)),
                ('Transport_methods', models.TextField(default='', max_length=200)),
                ('Suggestions', models.TextField(default='', help_text='Suggest something about the place. Example: The best food to try around this area (or) other places of interests around (or) Visitors food is not allowed', max_length=300)),
                ('State_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Profile.state')),
            ],
        ),
    ]
