# Generated by Django 3.1.4 on 2021-02-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0037_auto_20210213_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='points_of_interest',
            name='Suggestions',
            field=models.TextField(default='', help_text='Suggest something about the place. Example: The best food to try around this area (or) other places of interests around (or) Visitors food is not allowed', max_length=500),
        ),
        migrations.AlterField(
            model_name='points_of_interest',
            name='Tips',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='points_of_interest',
            name='Transport_methods',
            field=models.TextField(default='', max_length=300),
        ),
    ]
