# Generated by Django 3.1.4 on 2021-02-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0039_auto_20210214_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='slug',
            field=models.SlugField(default='state', max_length=100),
        ),
    ]
